language: java
jdk:
- oraclejdk8
script: mvn clean package
deploy:
  skip_cleanup: true
  provider: releases
  api_key:
    secure: SeWTLdBWX3v/IYs8bxzp7O2sUoJoj//66C01A3gbcogiazyL6jpmulmAoXbWQZC9yxdN7/1dDLAB1Cs4Imj26GKUStgNRl0diO1Wz7FHMuGH2FfDanmKn4r2J0MjqW0jrz9kkCQb0k3nhTnn1I4fK/gjoolkvdcC4ZsuY/MhWd6etQTv/llDRz5rHoLCwl/gqbj53mOo8yUREvza5UQfmdO8Vrp2NwYtol5q6jiOdThGcCWg5qbCBwascRIj2429xLSEZP100y4nNKnBnLA/XYeoNgdMJkMfdQ1BcKCHcaepraMqF70rTR0Nvo/MBZzqP/LBOf572BCh0VfQibTuVQ1p4H2ajjlIjPVUdVh0NLKPLp+JpdxwjfWXbEbMk76iRv6RRlj6oEhH/7I6V3+HF4J0Dw+UEvxr3l741qUdMNiEqJtocAPa8ekz1IMNrWH0x1gfkEBKf87wKH75cxAiUndnK+4R/4qdlHTVFe5FpfLnVMKT5QuVmeoRT4rWkfTb1bg+Kxo4pJ+1LMb2AT9vWfGKALT4Kkm6jagSE2Mu17jEqBygACK141HptwsWAk4ja4z5SW3rxanscKKiAqGmb1eEjFfA3KBgoenczoTmOFceG1hKtHCaXVPebm0Sq/BbYAf9WyLZfZlkqy+iN+vOSWCQcThqqS2p1xXIdzMsJw8=
  file: "/home/travis/build/bo0tzz/TopKekBot/target/TopKekBot.jar"
  on:
    repo: bo0tzz/TopKekBot
